- name: create volume
  shell: "docker volume create downloads"
- name: create volume
  shell: "docker volume create webcertificates"
- name: create volume
  shell: "docker volume create vpncertificates"
- name: create volume
  shell: "docker volume create dc"
- name: create volume
  shell: "docker volume create acme"
- name: create volume
  shell: "docker volume create letsencrypt"
- name: create volume
  shell: "docker volume create postgres"
- name: create volume
  shell: "docker volume create storagebackup"
- name: create volume
  shell: "docker volume create googledrivetriest"
- name: create volume
  shell: "docker volume create ldapcertificates"
- name: create volume
  shell: "docker volume create elasticsearch"
- name: create volume
  shell: "docker volume create mariadb"